print("Welcome")
print("to test program 1x1")
print("Hello, World!")
c= input("input number: ")
c=float(c)
print(c)
a= 15
print("a=15")
b=37
print("b=15")
print("a+b=")
e=print(a+b)
print("a+c=")
f=print(a+c)
print("b+c=")
g=print(b+c)
print("a-b=")
h=print(a-b)
print("a-c=")
i=print(a-c)
print("b-c=")
j=print(b-c)
print(e)